### ISSUE TITLE
AttributeError: 'Seq2SeqLMOutput' object has no attribute 'additional_lm_logits'

### ISSUE THREAD

**Issue by pruksmhc** [prajdabre/yanmtt#1]
After I follow the installation and run examples/train_mbart_model.sh, I get the below error. 

Loading from checkpoint
Traceback (most recent call last):
  File "pretrain_nmt.py", line 630, in <module>
    run_demo()
  File "pretrain_nmt.py", line 627, in run_demo
    mp.spawn(model_create_load_run_save, nprocs=args.gpus, args=(args,files,train_files,))         #
  File "/root/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/root/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/yanmtt/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/root/yanmtt/pretrain_nmt.py", line 359, in model_create_load_run_save
    if mod_compute.additional_lm_logits is not None:
AttributeError: 'Seq2SeqLMOutput' object has no attribute 'additional_lm_logits'

What may be going wrong?  The version of transformers I have is 4.3.2.

**Comment by prajdabre** [comment]
Hi,

Have you installed this version of transformers using pip or by using the modified version of the repo I provided?

This error occurs when you use the pip installed version.

Solution (in case the pip version is used):
Step 1: pip uninstall transformers
Step 2: cd <path to yanmtt>/transformers
Step 3: python setup.py install

Kindly let me know if it works for you.

**Comment by pruksmhc** [comment]
I did not use the pip installed version. I followed the above, but I'm still running into the same error.

**Comment by pruksmhc** [comment]
In fact, the first error I run into with examples/train_mbart_model.py is 

Traceback (most recent call last):
  File "pretrain_nmt.py", line 34, in <module>
    from transformers import AutoTokenizer, MBartTokenizer, MBart50Tokenizer, BartTokenizer
ImportError: cannot import name 'MBart50Tokenizer'

**Comment by prajdabre** [comment]
Hi,

I did a fresh install and I am able to successfully run all examples. So I am pretty sure there is a transformers version conflict.

I then tried to reproduce your error using the following steps:
1. Install the official transformers version using "pip install transformers==4.3.2"
2. Install my local transformers version using "cd yanmtt/transformers && python setup.py install"

When this is done, I get the same error as you do. This means that the previous version of transformers 4.3.2 which does not have my code changes takes priority. The only way to fix this is to remove all traces of transformers via MULTIPLE "pip uninstall transformers" and then install ONLY my version using "cd yanmtt/transformers && python setup.py install".

Note that if steps 1 and 2 are reversed then the pip version is not installed so there should not be an issue.

Additional details to check for multiple versions:
The way to check this is to look at "/root/yanmtt/py36/lib/python3.6/site-packages/" and see if there are multiple installations. If you have installed using my copy of transformers then you should see ONLY "/root/yanmtt/py36/lib/python3.6/site-packages/transformers-4.3.2-py3.6.egg". If there are other files/folders like: "/root/yanmtt/py36/lib/python3.6/site-packages/transformers-4.3.2.dist-info" or "/root/yanmtt/py36/lib/python3.6/site-packages/transformers" then that is most likely the source of your issue.

Explanation:
I have made changes to the transformers code and unless you use my changed code or if you have a version conflict then you wont be able to use "MBart50Tokenizer". The "Seq2SeqLMOutput" class has also been modified to have the attribute "additional_lm_logits" so if there is a version conflict then there will be an error.

Hope this helps.

**Comment by pruksmhc** [comment]
Ah, this is now working, thank you!

**Comment by prajdabre** [comment]
Thank you for reporting. This should help others :)
