### ISSUE TITLE
Train MBART Model: forward() got an unexpected keyword argument 'label_mask'

### ISSUE THREAD

**Issue by anhdungitvn** [prajdabre/yanmtt#18]
Scenario: 
- Run: `$ ./examples/train_mbart_model.sh`

Error:
`TypeError: forward() got an unexpected keyword argument 'label_mask'`

![image](https://user-images.githubusercontent.com/30354322/160223765-6533985e-961f-4944-8d55-c7e70e4953b3.png)

I'm looking forward to your reply. 
Thanks!

**Comment by prajdabre** [comment]
Hi,

Are you using the version of transformers provided with this toolkit, or did you install it using "pip install transformers?"

If you used the latter, then you will get this error.

To fix this: 
1. pip uninstall transformers
2. cd yanmtt/transformers
3. python setup.py install

**Comment by anhdungitvn** [comment]
Dear Dr. @prajdabre ,

Your answer solved my issue perfectly.

Thank you!
