### ISSUE TITLE
Invalid package reference in requirements.txt

### ISSUE THREAD

**Issue by ShivprasadSagare** [prajdabre/yanmtt#22]
https://github.com/prajdabre/yanmtt/blob/0bd9c06edae16e292f9f0c0419c30d2479fb9ae6/requirements.txt#L157

This line references a package using a file name that is not provided with the repo. Please resolve.

**Comment by prajdabre** [comment]
Please remove the line

**Comment by ShivprasadSagare** [comment]
Okay.
