### ISSUE TITLE
ImportError: cannot import name 'AutoTokenizer' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by nikhilbyte** [prajdabre/yanmtt#29]
Hi,
I followed the steps mentioned to install, but meet the following error when trying to run the pre-training command.
`ImportError: cannot import name 'AutoTokenizer' from 'transformers' (unknown location)
`
P.S:  I was able to install this library and do the pre-training a few weeks back but I tried to do it again and see the above error.

Thanks for your work.

**Comment by prajdabre** [comment]
Hi,

Did you make a fresh install, pull some recent changes or did you continue from your old installation?

**Comment by nikhilbyte** [comment]
I'm installing on colab so I made a fresh install.

**Comment by prajdabre** [comment]
This was not designed to work on colab. I am not sure how to help here!

**Comment by prajdabre** [comment]
Could you share your colab notebook? Maybe I can take a look and see what works.

**Comment by nikhilbyte** [comment]
Sure,
here:
https://colab.research.google.com/drive/19FfhcnNljVetasQywQMw0DwivCZQV3No?usp=sharing

**Comment by prajdabre** [comment]
I made some minor changes and it seems to work so far. I did not have the greek sentences file so training wont work but otherwise it seems to work now.

Main problems:
1. Figure out a way to have python version 3.6.8 which is the exact version needed to make the requirements.txt work properly
2. Try to use virtualenv rather than rely on the root environment

**Comment by nikhilbyte** [comment]
Thankyou so much.
The error went away but I got another error that I can't seem to work away.
`RuntimeError: The expanded size of the tensor (43) must match the existing size (38) at non-singleton dimension 1.  Target sizes: [105, 43, 1].  Tensor sizes: [105, 38, 1]
`
What causes this error do you have an idea?
Thanks

**Comment by prajdabre** [comment]
The default tokenizer you are using is for vietnamese, hindi and english and recognizes language ids such as en, hi or vi. You use gr which is unsupported. Please go through the flag descriptions and understand what they mean rather than use the code blindly.

**Comment by nikhilbyte** [comment]
So is it possible to do the pre-training for greek texts ? If so, how do I go about it ?
because there's no BART model trained for greek language. 
What do I pass in model and tokenizer if I want to trained the model from scratch for a completely new language ?

**Comment by prajdabre** [comment]
You can do it for any texts. The example scripts are just examples. You will have to suitably modify them for your purposes. 
1. You will have to make your own tokenizer.
2. You will have to train a model from scratch.

In both cases you will need to pass appropriate arguments to the python scripts mentioned in the example shell scripts.
