### ISSUE TITLE
Can it be used to pre-train a BART model?

### ISSUE THREAD

**Issue by Abigail61** [prajdabre/yanmtt#5]
Hi~
I want to find a method to pretrain a BART model with my own corpus. The pretrain method can add noise to the input and reconstruct the input, just as BART pre-training model did. But I couldn't find a specific way to pre-train the BART model, but came across this mBART pre-training method. Can it be used to pre-train the BART model?

Looking forward to your reply.

**Comment by prajdabre** [comment]
mBART and BART use the same technique. Except that the former uses monoolingual corpora for multiple languages and Bart  uses monoolingual corpora for a single language. So yes, you can do this using my toolkit. All you do is specify the corpus for a single language.
